### ISSUE TITLE
Installing on Windows still requires missing headers

### ISSUE THREAD

**Issue by davidh-ssec** [storpipfugl/pykdtree#12]
While making pykdtree more Windows compatible I ran in to appveyor requiring certain missing headers and fixed it by adding a special script: https://github.com/storpipfugl/pykdtree/commit/9ec7f63248c7d2a49bc3deb711e9d70d5614011b

However, now anyone using pykdtree in appveyor needs to make sure to also add these headers to their appveyor build. Since these headers are mostly type definitions maybe they should be added to pykdtree and specified directly in setup.py's compilation (on Windows machines only). Thoughts?

**Comment by davidh-ssec** [comment]
Likewise the new pykdtree from PyPI seems to cause pyresample tests to fail on travis for all environments. Due to the header stuff I'm not sure if appveyor succeeds, but I'm having trouble reproducing the pyresample failures.

**Comment by storpipfugl** [comment]
I've hidden release 1.2.0 from pypi so 1.1.1 should now be distributed again

**Comment by storpipfugl** [comment]
OK. I've found the problem: https://github.com/storpipfugl/pykdtree/commit/5e20c5298a581caaac5f4a3e329d5df48ca6fda2#diff-1a57f6cfdf2ae284f704e95d91dfbbb4R665

This means the "i" variable is no longer thread local for OpenMP (see http://supercomputingblog.com/openmp/tutorial-parallel-for-loops-with-openmp/). We need to add a "privat(i, j)" to the pragma (and do some testing with various number of openmp threads on a large dataset before releasing again)

**Comment by davidh-ssec** [comment]
@storpipfugl Thanks. When compiled with openmp, how does pykdtree decide to split the data up? Does it not split it unless the data is very large? Or does it run each for loop iteration in a separate process?

I'll do a quick test with pyresample and a separate pykdtree branch to see if I can make it work for pyresample at least on travis (I still can't reproduce the errors on my own machines).

**Comment by storpipfugl** [comment]
OpenMP slits the query point dataset in chunks of 100 (that's what the "100" in the "schedule" function means) and it very much seems it does not do any splitting at all if there is less than 100 query points (that's why the pykdtree tests all pass as they use only a few query points). So we need to add a test with say 250 query points to have a chance of catching errors like this

**Comment by davidh-ssec** [comment]
Ah ok I'll see if I can figure out how your tests are written. I think I've fixed the private variable issue.

This still doesn't really address the missing headers on appveyor.

**Comment by davidh-ssec** [comment]
@storpipfugl So I made the fix and proved that pyresample's test pass. I then made a test to hopefully use multiple processes by querying 450 points at once. Then to make sure that the test would have failed before the fix I cherry-picked the test commit to the old pre-master...and it passed?!?!? Could you look at this test and see if it works as expected:

https://github.com/davidh-ssec/pykdtree/blob/pre-master/pykdtree/test_tree.py#L272

**Comment by storpipfugl** [comment]
The test passes for me too forcing 4 OpenMP threads (OMP_NUM_THREADS=4 python setup.py nosetests). Unfortunately these errors are unpredictable by nature so when having thread safety problems it's quite common that the symptom is strange failures once in a while and otherwise expected behaviour.

I would suggest to use a significantly larger number of query points to increase the chance of provoking any threading error (say 50000) but otherwise the test looks fine

**Comment by storpipfugl** [comment]
@davidh-ssec thanks for the pull request. I've released v1.2.1

Regarding the original issue it's a bit unclear to me if it's an appveyor issue or a general problem when compiling on windows?

**Comment by davidh-ssec** [comment]
@storpipfugl My understanding is that it *can* be an issue with older Windows compilers. The headers should be included with MSVC 2010+. However, it seems some machines already have these headers and there are many places to get them from. Appveyor is not one of them.

I think asking users of older Windows machines to download the headers (maybe document it) if they need pykdtree for python 2.7 is not a terrible thing. Similarly requiring people add the headers to their appveyor setup if they are testing on python 2.7 isn't a huge deal for the few projects that may want to. This all assumes that new projects will stop supporting python 2.7 in the next year or so. I'm not really sure what the consequences might be if pykdtree-provided headers are used instead of existing system headers (on Windows only).

**Comment by storpipfugl** [comment]
@davidh-ssec it sounds like the right thing to do is to add a section to the readme on Windows install and appveyor testing. If you have the time to do that it will be great
