### ISSUE TITLE
This wont work on Mac OS Sierra

### ISSUE THREAD

**Issue by elec3647** [storpipfugl/pykdtree#19]
I found issues with this after I tried to compile py-sphviewer. What is worse, this installs without any errors using pip. I am going to try what I did for pysphviewer and see if it compiles this.

See <https://github.com/alejandrobll/py-sphviewer/issues/3> for similar issue.

```
$ python
Python 2.7.13 (default, Dec 18 2016, 07:03:39) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sphviewer
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/sphviewer/__init__.py", line 10, in <module>
    from Particles import Particles
  File "/usr/local/lib/python2.7/site-packages/sphviewer/Particles.py", line 6, in <module>
    from pykdtree.kdtree import KDTree # pykdtree by Esben S. Nielsen 
ImportError: dlopen(/usr/local/lib/python2.7/site-packages/pykdtree/kdtree.so, 2): Library not loaded: @rpath/libomp.dylib
  Referenced from: /usr/local/lib/python2.7/site-packages/pykdtree/kdtree.so
  Reason: image not found
```

**Comment by davidh-ssec** [comment]
@elec3647 Any idea what compiler your pip used when it installed pykdtree? I know this issue is old, but I was pretty sure the defaults in `setup.py` were changed to work better on OSX.

**Comment by storpipfugl** [comment]
Given the info so far I'll close this issue as being covered by #37 
Please reopen if this is not correctly understood
