### ISSUE TITLE
Missing query_ball_point

### ISSUE THREAD

**Issue by akaszynski** [storpipfugl/pykdtree#23]
Hello,

This is an excellent algorithm that's much faster than scipy for my nearest neighbor searches.  Thanks!

Would it be too much work to add `query_ball_point` that's currently in the scipy implementation?

Alex

**Comment by akaszynski** [comment]
Turns out that you can do much of the same functionality by setting the ```distance_upper_bound=``` to some number and then ignoring neighbors with infinite distance.  You still have to set the number of neighbors to find, but there's not too much of a time penalty to that.

**Comment by Mechazo11** [comment]
> Turns out that you can do much of the same functionality by setting the `distance_upper_bound=` to some number and then ignoring neighbors with infinite distance. You still have to set the number of neighbors to find, but there's not too much of a time penalty to that.

@akaszynski can you share the code that you used to replicate the functionality of query_ball_point() method?
