### ISSUE TITLE
Make a new release for pykdtree

### ISSUE THREAD

**Issue by mraspaud** [storpipfugl/pykdtree#45]
It would be nice if we could release a new version of pykdtree

**Comment by mraspaud** [comment]
@storpipfugl are you ok if I do a new release or do you want to it yourself ?

**Comment by mraspaud** [comment]
Ok, I'll make a release then...

**Comment by sbdt-google** [comment]
And upgrade the version number to 1.3.2.
The master has a few things beyond what was found in 1.3.1, for example: https://github.com/storpipfugl/pykdtree/pull/40
Being able to freeze will make it easier for us to upgrade, when we are forced to use a specific well defined version.
Thanks

**Comment by djhoese** [comment]
Version 1.3.5 is out now with Python 3.10 wheels and an sdist.
