### ISSUE TITLE
Set repository secrets

### ISSUE THREAD

**Issue by mraspaud** [storpipfugl/pykdtree#53]
After merging the PR for using github actions, we need to set up some repo secrets:
- login details test_pypi_username and test_pypi_password.
- login details pypi_username and pypi_password.

@storpipfugl you are the only one who can do this I think, could you have a look?

**Comment by djhoese** [comment]
Note I would guess you could set up a token for this so you don't have to put your password in a secret on github.

**Comment by storpipfugl** [comment]
I've add secrets for pypi_username and pypi_password. There's no pykdtree project on test.pypi.org

**Comment by mraspaud** [comment]
@storpipfugl would be great if you could create it!
