### ISSUE TITLE
arm64

### ISSUE THREAD

**Issue by philippemiron** [storpipfugl/pykdtree#61]
Is there a plan to bring this package to [miniforge](https://github.com/conda-forge/miniforge), which supports arm64 processor (like the Apple M1)? I saw it's available on [Ubuntu](https://ubuntu.pkgs.org/20.04/ubuntu-universe-arm64/python3-pykdtree_1.3.1-4build2_arm64.deb.html) so I guess it should be simple to bring to miniforge.

**Comment by djhoese** [comment]
Miniforge is powered by the packages on conda-forge. The pykdtree package on conda-forge should support ARM as of December 2021 (from what I can tell). If that doesn't seem to be the case please comment and we can reopen this.
