### ISSUE TITLE
installation on OSX complains about -fopenmp even with USE_OMP=0

### ISSUE THREAD

**Issue by northaholic** [storpipfugl/pykdtree#8]
i tried installing pykdtree on OSX with the environmental variable `USE_OMP `set as `export USE_OMP=0`

`sudo python setup.py develop --user`

fails with an error

```
gcc-4.2 not found, using clang instead
building 'pykdtree.kdtree' extension
clang -fno-strict-aliasing -fno-common -dynamic -arch i386 -arch x86_64 -g -O2 -DNDEBUG -g -O3 -I/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -I/Volumes/MacBook Pro/Users/joro/Work/pykdtree/.eggs/numpy-1.11.1rc1-py2.7-macosx-10.6-x86_64.egg/numpy/core/include -c pykdtree/kdtree.c -o build/temp.macosx-10.6-x86_64-2.7/pykdtree/kdtree.o -std=c99 -O3 -fopenmp
clang: error: unsupported option '-fopenmp'
clang: error: unsupported option '-fopenmp'
error: command 'clang' failed with exit status 1
```

**Comment by storpipfugl** [comment]
This is actually a *nix sudo feature of not preserving environment variables by default in a sudo session.

See
$ USE_OMP=0 sudo bash -c 'echo $USE_OMP'
vs.
$ USE_OMP=0 sudo -E bash -c 'echo $USE_OMP'

It is however relevant to get support for/ test coverage of both OpenMP enabled compilation and the clang complier. Closing and opening new issue for this.
